{"name": "Проверка валидности поля Повтор пароля", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 10s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(text(),'недопустимый пароль')]\")).text\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(text(),'недопустимый пароль')]\"}\n  (Session info: chrome=113.0.5672.94)\n\nScreenshot: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.png\nPageSource: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.html", "trace": "venv\\lib\\site-packages\\selene\\core\\wait.py:102: in for_\n    return fn(self._entity)\nvenv\\lib\\site-packages\\selene\\core\\wait.py:56: in __call__\n    return self._fn(entity)\nvenv\\lib\\site-packages\\selene\\core\\query.py:47: in <lambda>\n    text: Query[Element, str] = Query('text', lambda element: element().text)\nvenv\\lib\\site-packages\\selene\\core\\entity.py:179: in __call__\n    return self._locator()\nvenv\\lib\\site-packages\\selene\\core\\locator.py:34: in __call__\n    return self._locate()\nvenv\\lib\\site-packages\\selene\\core\\entity.py:1529: in <lambda>\n    f'{self}.element({by})', lambda: self.driver.find_element(*by)\nvenv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:976: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\nvenv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:321: in execute\n    self.error_handler.check_response(response)\nvenv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:242: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(text(),'недопустимый пароль')]\"}\nE     (Session info: chrome=113.0.5672.94)\n\nDuring handling of the above exception, another exception occurred:\ntests\\test_login.py:125: in test_field_repeat_password\n    page.registration_field_repeat_password()\npages\\home.py:271: in registration_field_repeat_password\n    message_error = self.get_element_text(self.message_error_repeat_password_text_var, \"Текст ошибки поля повторить пароль не верный или текст отсутствует\")\npages\\base.py:27: in get_element_text\n    return element.get(query.text)\nvenv\\lib\\site-packages\\selene\\core\\entity.py:116: in get\n    return self.wait.for_(query)\nvenv\\lib\\site-packages\\selene\\core\\wait.py:125: in for_\n    raise self._hook_failure(failure)\nE   selene.core.exceptions.TimeoutException: Message: \nE   \nE   Timed out after 10s, while waiting for:\nE   browser.element(('xpath', \"//div[contains(text(),'недопустимый пароль')]\")).text\nE   \nE   Reason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(text(),'недопустимый пароль')]\"}\nE     (Session info: chrome=113.0.5672.94)\nE   \nE   Screenshot: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.png\nE   PageSource: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.html"}, "steps": [{"name": "Нажать Аккаунт", "status": "passed", "start": 1684320453928, "stop": 1684320453971}, {"name": "Нажать Зарегистрироваться", "status": "passed", "start": 1684320453971, "stop": 1684320454132}, {"name": "Валидация поля Повторить Пароль", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 10s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(text(),'недопустимый пароль')]\")).text\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(text(),'недопустимый пароль')]\"}\n  (Session info: chrome=113.0.5672.94)\n\nScreenshot: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.png\nPageSource: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.html\n\n", "trace": "  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\pages\\home.py\", line 271, in registration_field_repeat_password\n    message_error = self.get_element_text(self.message_error_repeat_password_text_var, \"Текст ошибки поля повторить пароль не верный или текст отсутствует\")\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\pages\\base.py\", line 27, in get_element_text\n    return element.get(query.text)\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\venv\\lib\\site-packages\\selene\\core\\entity.py\", line 116, in get\n    return self.wait.for_(query)\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\venv\\lib\\site-packages\\selene\\core\\wait.py\", line 125, in for_\n    raise self._hook_failure(failure)\n"}, "steps": [{"name": "Заполнение поля '' текстом ''wer23''", "status": "passed", "parameters": [{"name": "element", "value": "<selene.core.entity.Element object at 0x000002BB4ED2C7F0>"}, {"name": "text", "value": "'wer23'"}, {"name": "fieldName", "value": "''"}], "start": 1684320454132, "stop": 1684320454228}, {"name": "Взять текст из элемента ''Текст ошибки поля повторить пароль не верный или текст отсутствует''", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 10s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(text(),'недопустимый пароль')]\")).text\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(text(),'недопустимый пароль')]\"}\n  (Session info: chrome=113.0.5672.94)\n\nScreenshot: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.png\nPageSource: file://C:\\Users\\Qasquad1\\.selene\\screenshots\\1684320339655\\1684320339657.html\n\n", "trace": "  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\pages\\base.py\", line 27, in get_element_text\n    return element.get(query.text)\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\venv\\lib\\site-packages\\selene\\core\\entity.py\", line 116, in get\n    return self.wait.for_(query)\n  File \"C:\\Users\\Qasquad1\\PycharmProjects\\lime-qa\\venv\\lib\\site-packages\\selene\\core\\wait.py\", line 125, in for_\n    raise self._hook_failure(failure)\n"}, "parameters": [{"name": "element", "value": "<selene.core.entity.Element object at 0x000002BB4ED2EC70>"}, {"name": "allureText", "value": "'Текст ошибки поля повторить пароль не верный или текст отсутствует'"}], "start": 1684320461275, "stop": 1684320471802}], "start": 1684320454132, "stop": 1684320471802}], "attachments": [{"name": "Скринтшот", "source": "c154c5f7-d755-46f5-bfa4-866e4f5aede5-attachment.png", "type": "image/png"}, {"name": "Логи консоли", "source": "d3f828c9-530e-4494-9008-ff33cb6ff0a1-attachment.json", "type": "application/json"}, {"name": "log", "source": "af1b524b-9a2b-47f9-9b00-9095977fbbd3-attachment.txt", "type": "text/plain"}], "start": 1684320453928, "stop": 1684320471803, "uuid": "aa51fc0f-9c33-46ab-9965-1f06e8ab29d3", "historyId": "2395a9b2a2c906142f6768d7c5d88907", "testCaseId": "19208eadd6ac9712b22d1ff353e8cf28", "fullName": "tests.test_login.TestLogin#test_field_repeat_password", "labels": [{"name": "feature", "value": "Тесты логина"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-VLT8PU4"}, {"name": "thread", "value": "12164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}